name: Pipeline

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  Params:
    uses: pyTooling/Actions/.github/workflows/Parameters.yml@r0
    with:
      name: pyVHDLModel

  UnitTesting:
    uses: pyTooling/Actions/.github/workflows/UnitTesting.yml@r0
    needs:
      - Params
    with:
      jobs: ${{ needs.Params.outputs.python_jobs }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}

  Coverage:
    uses: pyTooling/Actions/.github/workflows/CoverageCollection.yml@r0
    needs:
      - Params
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
    secrets:
      codacy_token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  StaticTypeCheck:
    uses: pyTooling/Actions/.github/workflows/StaticTypeCheck.yml@r0
    needs:
      - Params
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      requirements: '-r tests/requirements.txt'
      commands: mypy --html-report htmlmypy -p pyVHDLModel
      report: 'htmlmypy'
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.typing }}

  PublishTestResults:
    uses: pyTooling/Actions/.github/workflows/PublishTestResults.yml@r0
    needs:
      - UnitTesting

  Package:
    uses: pyTooling/Actions/.github/workflows/Package.yml@r0
    needs:
      - Params
      - Coverage
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.package }}

  Release:
    uses: pyTooling/Actions/.github/workflows/Release.yml@r0
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - UnitTesting
      - Coverage
      - StaticTypeCheck
      - Package

  PublishOnPyPI:
    uses: pyTooling/Actions/.github/workflows/PublishOnPyPI.yml@r0
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - Params
      - Release
      - Package
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      requirements: -r dist/requirements.txt
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.package }}
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  VerifyDocs:
    needs:
      - Params
    name: 👍 Verify example snippets using Python ${{ fromJson(needs.Params.outputs.params).python_version }}
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v2

      - name: ⚙ Setup GHDL
        uses: ghdl/setup-ghdl-ci@master

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ fromJson(needs.Params.outputs.params).python_version }}

      - name: 🐍 Install dependencies
        run: |
          pip3 install git+https://github.com/ghdl/ghdl.git@$(ghdl version hash)

      - name: ✂ Extract code snippet from README
        shell: python
        run: |
          from pathlib import Path
          import re

          ROOT = Path('.')

          with (ROOT / 'README.md').open('r') as rptr:
              content = rptr.read()

          m = re.search(r"```py(thon)?(?P<code>.*?)```", content, re.MULTILINE|re.DOTALL)

          if m is None:
              raise Exception("Regular expression did not find the example in the README!")

          with (ROOT / 'tests/docs/example.py').open('w') as wptr:
              wptr.write(m["code"])

#      - name: Print example.py
#        run: cat tests/docs/example.py

      - name: ☑ Run example snippet
        working-directory: tests/docs
        run: |
          python3 example.py

  BuildTheDocs:
    uses: pyTooling/Actions/.github/workflows/BuildTheDocs.yml@r0
    needs:
      - Params
      - VerifyDocs
    with:
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}

  PublishToGitHubPages:
    uses: pyTooling/Actions/.github/workflows/PublishToGitHubPages.yml@r0
    needs:
      - Params
      - BuildTheDocs
      - Coverage
      - StaticTypeCheck
    with:
      doc: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}
      coverage: ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
      typing: ${{ fromJson(needs.Params.outputs.params).artifacts.typing }}

  ArtifactCleanUp:
    uses: pyTooling/Actions/.github/workflows/ArtifactCleanUp.yml@r0
    needs:
      - Params
      - UnitTesting
      - Coverage
      - StaticTypeCheck
      - BuildTheDocs
      - PublishToGitHubPages
      - PublishTestResults
    with:
      package: ${{ fromJson(needs.Params.outputs.params).artifacts.package }}
      remaining: |
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-ubuntu-3.7
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-ubuntu-3.8
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-ubuntu-3.9
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-ubuntu-3.10
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-windows-3.7
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-windows-3.8
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-windows-3.9
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-windows-3.10
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-msys2-3.9
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-macos-3.7
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-macos-3.8
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-macos-3.9
        ${{ fromJson(needs.Params.outputs.params).artifacts.unittesting }}-macos-3.10
        ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
        ${{ fromJson(needs.Params.outputs.params).artifacts.typing }}
        ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}
