name: Unit Testing, Coverage Collection, Package, Release, Documentation and Publish

on: 
  push:
  workflow_dispatch:

jobs:

  Params:
    uses: pyTooling/Actions/.github/workflows/Params.yml@dev
    with:
      name: pyVHDLModel

  UnitTesting:
    uses: pyTooling/Actions/.github/workflows/UnitTesting.yml@dev
    needs:
      - Params
    with:
      jobs: ${{ needs.Params.outputs.python_jobs }}
      TestReport: true

  Coverage:
    uses: pyTooling/Actions/.github/workflows/CoverageCollection.yml@dev
    needs:
      - Params
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
    secrets:
      codacy_token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  Release:
    uses: pyTooling/Actions/.github/workflows/Release.yml@dev
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - UnitTesting
      - Coverage

  Package:
    uses: pyTooling/Actions/.github/workflows/Package.yml@dev
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - Params
      - Coverage
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.wheel }}

  PublishOnPyPI:
    uses: pyTooling/Actions/.github/workflows/PublishOnPyPI.yml@dev
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - Params
      - Release
      - Package
    with:
      python_version: ${{ fromJson(needs.Params.outputs.params).python_version }}
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.wheel }}
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}


  VerifyDocs:
    needs:
      - Params
    name: 👍 Verify example snippets using Python ${{ fromJson(needs.Params.outputs.params).python_version }}
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v2

      - name: ⚙ Setup GHDL
        uses: ghdl/setup-ghdl-ci@master

      - name: 🐍 Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ fromJson(needs.Params.outputs.params).python_version }}

      - name: 🐍 Install dependencies
        run: |
          pip3 install git+https://github.com/ghdl/ghdl.git@$(ghdl version hash)

      - name: ✂ Extract code snippet from README
        shell: python
        run: |
          from pathlib import Path
          import re

          ROOT = Path('.')

          with (ROOT / 'README.md').open('r') as rptr:
              content = rptr.read()

          m = re.search(r"```py(thon)?(?P<code>.*?)```", content, re.MULTILINE|re.DOTALL)

          if m is None:
              raise Exception("Regular expression did not find the example in the README!")

          with (ROOT / 'tests/docs/example.py').open('w') as wptr:
              wptr.write(m["code"])

#      - name: Print example.py
#        run: cat tests/docs/example.py

      - name: ☑ Run example snippet
        working-directory: tests/docs
        run: |
          python3 example.py


  BuildTheDocs:
    uses: pyTooling/Actions/.github/workflows/BuildTheDocs.yml@dev
    needs:
      - Params
      - VerifyDocs
    with:
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}

  PublishToGitHubPages:
    uses: pyTooling/Actions/.github/workflows/PublishToGitHubPages.yml@dev
    needs:
      - Params
      - BuildTheDocs
      - Coverage
    with:
      doc: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}
      coverage: ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}


  ArtifactCleanUp:
    name: 🗑️ Artifact Cleanup
    runs-on: ubuntu-latest

    needs:
      - Params
      - Coverage
      - PublishToGitHubPages

    steps:
      - name: 🗑️ Delete all Artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            ${{ fromJson(needs.Params.outputs.params).artifacts.coverage }}
            ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}
